#pragma once

#include <QMetaType>
#include <QString>

namespace localization {
enum class Language
{
    English = 0,
    German = 1,
};

enum class Text
{
    AppStarted,
    LanguageChanged,
    Ready,

    TabDashboard,
    TabProjects,
    TabSteam,
    TabItch,
    TabLogs,
    TabSettings,

    DashboardTitle,
    ManagedProjects,
    ReadyBuilds,
    SteamUploads,
    ItchUploads,
    Placeholder,
    QuickActions,
    NewProject,
    SelectBuildFolder,
    PrepareSteamUpload,
    PrepareItchUpload,

    ProjectsTitle,
    SaveSettings,
    ProjectList,
    SelectedProject,
    ProjectPrefix,
    BuildPrefix,
    VersionPrefix,
    TargetsPrefix,
    UpdatedPrefix,
    Changelog,
    ProjectName,
    ProjectRoot,
    BuildDirectory,
    UploadTargets,
    LastUpdated,
    DeleteProject,
    NoProjects,
    Project,
    Browse,

    SteamTitle,
    SteamProject,
    SteamCmdPlaceholder,
    SteamCmdPath,
    ContentBuilderPath,
    AppId,
    DepotId,
    BuildPath,
    BuildDescription,
    DepotConfiguration,
    SteamConfiguration,
    Branch,
    PreviewBuild,
    AddDepot,
    RemoveDepot,
    SteamLogin,
    SteamPassword,
    ShowPassword,
    SavePassword,
    ViewLogsFolder,
    SteamProgressReady,
    SteamProgressValidating,
    SteamProgressValidated,
    SteamProgressSaving,
    SteamProgressSaved,
    SteamProgressGenerating,
    SteamProgressGenerated,
    SteamProgressUploading,
    SteamProgressComplete,
    SteamProgressFailed,
    ValidateConfig,
    GenerateVdf,
    UploadToSteam,

    ItchTitle,
    ButlerPlaceholder,
    ButlerPath,
    UserGame,
    Channel,
    Version,
    CheckStatus,
    PushWithButler,

    LogsTitle,
    LogOutput,
    Clear,

    SettingsTitle,
    ApplicationSettings,
    WorkspaceFolder,
    Language,
    Theme,
    UseDarkTheme,
    English,
    German,

    LogDashboardNewProject,
    LogDashboardBuildFolder,
    LogDashboardSteamUpload,
    LogDashboardItchUpload,
    LogProjectsNewProject,
    LogProjectsBuildFolder,
    LogProjectsSave,
    LogProjectsSelected,
    LogProjectsCreated,
    LogProjectsDeleted,
    LogProjectsNoProjectSelected,
    LogSteamProjectSaved,
    LogSteamNoProjectSelected,
    LogSteamValidate,
    LogSteamGenerateVdf,
    LogSteamVdfGenerated,
    LogSteamUpload,
    LogSteamUploadStarted,
    LogSteamUploadFinished,
    LogSteamUploadFailed,
    LogSteamDepotAdded,
    LogSteamDepotRemoved,
    LogItchValidate,
    LogItchStatus,
    LogItchUpload,
    LogSettingsSave,
};

[[nodiscard]] QString translate(Language language, Text text);
[[nodiscard]] QString languageName(Language language, Language displayLanguage);
}

Q_DECLARE_METATYPE(localization::Language)
